### ISSUE TITLE
已知图片宽高比，如何让图片根据宽度自适应高度

### ISSUE THREAD

**Issue by stupidehorizon** [stupidehorizon/blog#10]
## 背景

相信大家在浏览网页时经常会遇到图片加载完后网页跳动的问题，这是因为网页初始化渲染完后图片还没有加载完，随着图片的加载网页高度会不停的跳动造成极差的用户体验，或者如果你想监听网页高度的滚动位置，然后去做某些事情时，就不得不去做一些 hack 让图片加载完后再去绑定滚动事件，否则就容易造成监听位置错误的问题。这个时候你可能会想就不能一开始就设置好图片的高度吗？在宽度固定的网页下这确实能解决问题，但是在响应式网站下，网页宽度会随着设备变化，所以图片的宽度会随着网页变化，而图片的高度又会随着宽度变化。

## 解决方案

解决方案其实很简单，但是对于没有经验的人来说可能会有点想不到。

### HTML

需要在图片容器组件的 style 属性的 padding-bottom 上指定图片的宽高比的百分比

```html
<div class="auto-height-container" style="padding-bottom: 80%">
    <img src="//mi.xiguacity.cn/fe-xigua/about/CSTA.png">
</div>
```

### SCSS

```scss
.auto-height-container {
  height: 0;
  overflow: hidden;
  position: relative;

  img,video {
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
  }
}
```

## 原理

元素不论什么方向的 margin 和 padding 的百分比都是基于包含块的宽度[MDN链接](https://developer.mozilla.org/en-US/docs/Web/CSS/padding)
![image](https://user-images.githubusercontent.com/20657809/52037866-4ae8a600-256b-11e9-878f-0035ed55afcb.png)

所以只要我们知道图片的宽高比我们就能根据图片所占宽度计算出图片的高度，从而避免了网页高度的跳动。
