### ISSUE TITLE
使用 CSS3 画一个立方体

### ISSUE THREAD

**Issue by stupidehorizon** [stupidehorizon/blog#2]
# 使用CSS3画一个立方体

最近面试有问道一些关于 CSS3 新特性的问题，因为最近平时虽然了解过很多，但是基本没怎么写过。所以这次就写一个 demo 熟悉一下 CSS3 的一些新特性。
#### 1. 首先搭建框架
```html
<div class="stage">
            <div class="content">
                <svg   id="cubic1" xmlns="http://www.w3.org/2000/svg" >
                    <rect   height="200" width="200" />
                    <text x="90px" y="110px" fill="red">1</text>
                </svg>
                <svg   id="cubic2" xmlns="http://www.w3.org/2000/svg" >
                    <rect   height="200" width="200" />
                    <text x="90px" y="110px" fill="red">2</text>
                </svg>
                <svg   id="cubic3" xmlns="http://www.w3.org/2000/svg" >
                    <rect   height="200" width="200" />
                    <text x="90px" y="110px" fill="red">3</text>
                </svg>
                <svg   id="cubic4" xmlns="http://www.w3.org/2000/svg" >
                    <rect   height="200" width="200" />
                    <text x="90px" y="110px" fill="red">4</text>
                </svg>
                <svg   id="cubic5" xmlns="http://www.w3.org/2000/svg" >
                    <rect   height="200" width="200" />
                    <text x="90px" y="110px" fill="red">5</text>
                </svg>
                <svg   id="cubic6" xmlns="http://www.w3.org/2000/svg" >
                    <rect   height="200" width="200" />
                    <text x="90px" y="110px" fill="red">6</text>
                </svg>
            </div>
        </div>
```      
这里使用了 SVG 正好也可以了解一下 SVG 的初步使用方法。   

### 2. 初始样式
```css
    .stage {width: 800px; height: 600px; background:#e5fffb; perspective:1000px;}
    .content{transform-style: preserve-3d;width: 100%;height: 100%;animation: clockwise 5s linear infinite}
    #cubic1{fill:#2ADF8A;}
    #cubic2{fill:#61BFBE;}
    #cubic3{fill:#BADDD6;}
    #cubic4{fill:#FFB5BA;}
    #cubic5{fill:#866667;}
    #cubic6{fill:#8BD15C;}
    SVG {position: absolute;top:200px; left:300px;width:200px; height:200px;}
    text{font-size: 60px;}
```   

这里很容易看懂就是把6个面都叠加到了 stage 中间。需要注意的是 perspective 表示观察点到z=0平面的距离。三维元素在观察者后面的部分不会绘制出来，即z轴坐标值大于 perspective 属性值的部分。另外可以简单的理解 perspective-origin，表示观察者的位置。默认值50%，50%表示正前方。
**perspective-origin 默认的情况**
![默认情况](http://wx3.sinaimg.cn/mw690/005NdwvWly1fk0i1aenjfj30rk0kuglv.jpg "默认情况")
**perspective-origin:0 ,0 的情况**
![0%，0%的情况](http://wx2.sinaimg.cn/mw690/005NdwvWly1fk0i2ewlu6j30rn0l3wex.jpg "0%，0%的情况")
就像是从左上方观察一个立方体，需要注意的是 perspective: 观察者据z=0平面的距离和 perspective-origin 观察的位置将共同决定物体被观察到的具体形状。
### 3. 形成正方体
讲完了 perspective-origin 和 perspective，下面就来讲如何形成一个立方体的形状。以第3面为例，这里是最上面那一面。
`#cubic3{fill:#BADDD6;transform: rotateX(90deg) translateZ(100px);}`
首先沿X轴旋转90度（逆时针），需要注意的是，旋转后物体的坐标轴是同时跟着旋转的，所以这时原本Z轴平行屏幕向上，translateZ(100px)向Z轴上方平移100px，到达指定位置。
其他同理
```css
    #cubic1{fill:#2ADF8A;transform: translateZ(100px);}
    #cubic2{fill:#61BFBE;transform:rotateY(180deg) translateZ(100px)}
    #cubic3{fill:#BADDD6;transform: rotateX(90deg) translateZ(100px);}
    #cubic4{fill:#FFB5BA;transform: rotateX(270deg) translateZ(100px);}
    #cubic5{fill:#866667;transform: rotateY(270deg) translateZ(100px);}
    #cubic6{fill:#8BD15C;transform: rotateY(90deg) translateZ(100px);}
```   

这是一个立方体就形成了，见第一张图。然后再加一点动画就大功搞成。   
### 4. 添加旋转动画
```css
 @keyframes clockwise{
        to{transform: rotateY(-360deg)}
    }
 .content{transform-style: preserve-3d;width: 100%;height: 100%;animation: clockwise 5s linear infinite}
```   

![](http://wx2.sinaimg.cn/mw690/005NdwvWly1fk0j3e7n8ag30rl0k0tgx.gif)

至此就全部结束啦。
